export const STATES_LIST = [
    { label: 'Select State', value: '' },
    { label: 'Andhra Pradesh', value: 'AndhraPradesh' },
    { label: 'Arunachal Pradesh', value: 'ArunachalPradesh' },
    { label: 'Assam', value: 'Assam' },
    { label: 'Bihar', value: 'Bihar' },
    { label: 'Chhattisgarh', value: 'Chhattisgarh' },
    { label: 'Goa', value: 'Goa' },
    { label: 'Gujarat', value: 'Gujarat' },
    { label: 'Haryana', value: 'Haryana' },
    { label: 'Himachal Pradesh', value: 'HimachalPradesh' },
    { label: 'Jharkhand', value: 'Jharkhand' },
    { label: 'Karnataka', value: 'Karnataka' },
    { label: 'Kerala', value: 'Kerala' },
    { label: 'Madhya Pradesh', value: 'MadhyaPradesh' },
    { label: 'Maharashtra', value: 'Maharashtra' },
    { label: 'Manipur', value: 'Manipur' },
    { label: 'Meghalaya', value: 'Meghalaya' },
    { label: 'Mizoram', value: 'Mizoram' },
    { label: 'Nagaland', value: 'Nagaland' },
    { label: 'Odisha', value: 'Odisha' },
    { label: 'Punjab', value: 'Punjab' },
    { label: 'Rajasthan', value: 'Rajasthan' },
    { label: 'Sikkim', value: 'Sikkim' },
    { label: 'Tamil Nadu', value: 'TamilNadu' },
    { label: 'Telangana', value: 'Telangana' },
    { label: 'Tripura', value: 'Tripura' },
    { label: 'Uttar Pradesh', value: 'UttarPradesh' },
    { label: 'Uttarakhand', value: 'Uttarakhand' },
    { label: 'West Bengal', value: 'WestBengal' },
    { label: 'Andaman and Nicobar Islands', value: 'AndamanAndNicobarIslands' },
    { label: 'Chandigarh', value: 'Chandigarh' },
    { label: 'Dadra and Nagar Haveli and Daman and Diu', value: 'DadraAndNagarHaveliAndDamanAndDiu' },
    { label: 'Lakshadweep', value: 'Lakshadweep' },
    { label: 'Delhi', value: 'Delhi' },
    { label: 'Puducherry', value: 'Puducherry' },
];

const AndhraPradesh = [
    { label: 'Anantapur', value: 'Anantapur' },
    { label: 'Chittoor', value: 'Chittoor' },
    { label: 'East Godavari', value: 'EastGodavari' },
    { label: 'Guntur', value: 'Guntur' },
    { label: 'Krishna', value: 'Krishna' },
    { label: 'Kurnool', value: 'Kurnool' },
    { label: 'Nellore', value: 'Nellore' },
    { label: 'Prakasam', value: 'Prakasam' },
    { label: 'Srikakulam', value: 'Srikakulam' },
    { label: 'Visakhapatnam', value: 'Visakhapatnam' },
    { label: 'Vizianagaram', value: 'Vizianagaram' },
    { label: 'West Godavari', value: 'WestGodavari' },
    { label: 'YSR Kadapa', value: 'YSRKadapa' },
];

export const DISTRICTS = {
    AndhraPradesh,
};

const Anantapur = [
    { label: 'Anantapur', value: 'Anantapur' },
    { label: 'Dharmavaram', value: 'Dharmavaram' },
    { label: 'Hindupur', value: 'Hindupur' },
    { label: 'Guntakal', value: 'Guntakal' },
    { label: 'Tadpatri', value: 'Tadpatri' },
    { label: 'Kadiri', value: 'Kadiri' },
    { label: 'Rayadurg', value: 'Rayadurg' },
    { label: 'Kalyandurg', value: 'Kalyandurg' },
    { label: 'Uravakonda', value: 'Uravakonda' },
    { label: 'Gooty', value: 'Gooty' },
    { label: 'Dhenukonda', value: 'Dhenukonda' },
    { label: 'Puttaparthi', value: 'Puttaparthi' },
];

export const CITIES = {
    Anantapur,
};
